server.port=8083
spring.application.name=comments-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dmsdb}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASS:safiasafia}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
